# Use the official OpenJDK 21 base image
FROM openjdk:21

# Expose port 8088 (or whatever port your application uses)
EXPOSE 8088

# Copy the Spring Boot application JAR file into the container
ADD target/demo1.jar /demo1.jar

# Specify the command to run the JAR file when the container starts
ENTRYPOINT ["java", "-jar", "/demo1.jar"]
